# Generated by Django 6.0.3 on 2026-03-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_produto_options_alter_produto_atualizado_em_and_more'),
        ('purchases', '0002_alter_fornecedor_options_alter_fornecedor_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.produto'),
        ),
    ]
