# Generated by Django 6.0.3 on 2026-03-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_itemcompra_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='historico_pagamentos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='justificativa_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('atrasado', 'Atrasado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=10),
        ),
    ]
