# Generated by Django 6.0.3 on 2026-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_fornecedor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero_nota_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
