# Generated by Django 6.0.3 on 2026-03-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_itemvenda_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
    ]
