# Generated by Django 6.0.3 on 2026-03-18 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_produto_options_alter_produto_atualizado_em_and_more'),
        ('sales', '0005_alter_itemvenda_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.produto'),
        ),
    ]
