# Generated by Django 6.0.3 on 2026-03-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeDeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('sigla', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_atual', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('estoque_maximo', models.PositiveIntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='products.categoria')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='products.unidadedemedida')),
            ],
        ),
    ]
