# Generated by Django 6.0.3 on 2026-03-18 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_produto_options_alter_produto_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='products.unidadedemedida', verbose_name='Unidade de Medida'),
        ),
    ]
